### ISSUE TITLE
`UIDeviceBatteryState` compile error when using framework with Swift 3

### ISSUE THREAD

**Issue by mirkofetter** [SensingKit/SensingKit-iOS#11]
I had an issue when using the SensingKit.framework in a Swift project. The compiler complained that SKBatteryData.h is using the unknown type `UIDeviceBatteryState`. Adding  `#import <UIKit/UIKit.h>` to SKBatteryData.h fixed it for me. I do not know if this solution is a good practise, as i am new to Swift programming.

**Comment by minoskt** [comment]
Hi @mirkofetter 

Thank you for reporting this issue. I added this fix and will be included in the next version v0.5 coming in a few days. Feel free to test it, it is available in `next` branch.

Best regards
Minos
