### ISSUE TITLE
problem with test code 

### ISSUE THREAD

**Issue by amro153** [SensingKit/SensingKit-iOS#13]
let batteryData = sensorData as! SKBattery it give warning 

"28:46: Cast from 'SKSensorData?' to unrelated type 'SKBattery' always fails"

**Comment by minoskt** [comment]
Hello

You are trying to cast sensor data as an actual sensor that is wrong. The correct way doing this is:
`let batteryData = sensorData as! SKBatteryData`

I hope that helps.

**Comment by amro153** [comment]
]Dear, 
Thank you for response 

The problem with this line 

let batteryData = sensorData as! SKBatteryData
  When I try it in objective c it run ok and sensor read without problem but swift give me an error 

SKBatteryData *batteryData = (SKBatteryData *)sensorData;   //run ok 
let batteryData = sensorData as! SKBatteryData.      // give error with cast

**Comment by minoskt** [comment]
Could you please try the following code? I can confirm that it works without issues in Xcode 8.3.3 (also in Xcode9 beta5).

```swift
import UIKit
import SensingKit

class ViewController: UIViewController {
    
    let sensingkit = SensingKitLib.shared()

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        if sensingkit.isSensorAvailable(SKSensorType.Battery) {
            
            do {
            
                try sensingkit.register(SKSensorType.Battery)
            
            }
            catch {
                
            }
            
            do {
                
                try sensingkit.subscribe(to: SKSensorType.Battery, withHandler: { (sensorType, sensorData, error) in
                    
                    if (error != nil) {
                        let batteryData = sensorData as! SKBatteryData
                        print("Battery Level: \(batteryData)")
                    }
                })
            }
            catch {
                
            }
            
            do {
                try sensingkit.startContinuousSensingWithAllRegisteredSensors()
            }
            catch {
                
            }
            
        }
    }

}
```
