### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by imolowkey** [SensingKit/SensingKit-iOS#16]
for example if I need to update after N second by each sensor how should I do this ? 

`   self.motionManager.gyroUpdateInterval = 10;// 1.0 / gyroscopeConfiguration.sampleRate;  // Convert Hz into interval`
I’ve found as you’ve defined "sampleRate" as ZSUInteger it causes issue , I believe if you will define it as float, it will work fine.

**Comment by minoskt** [comment]
Hello. This parameter represents the sampling rate in Hz. That means that a sampling rate of 100 Hz would mean that the sensor will collect 100 samples (events) per second.
