### ISSUE TITLE
Using magnetometer can we detect hidden camera ?

### ISSUE THREAD

**Issue by Manigandasaravanan** [SensingKit/SensingKit-iOS#17]
I use the magnetometer to read the deflection of Magnetic field X, Y and Z values. The values getting changed when I bring mobile close to the camera. Also, it's changing when I bring close to some other electronic devices. 

Is there any range to detect only for the camera ??

**Comment by minoskt** [comment]
I haven't tried that, but I guess you could try building an ML classifier that detects a camera from magnetometer data.
