### ISSUE TITLE
Running on background

### ISSUE THREAD

**Issue by mychaelgo** [SensingKit/SensingKit-iOS#18]
for pedometer sensor, is it can be run on background? (even the app is suspended or closed)

**Comment by minoskt** [comment]
Hello, and sorry for such late reply.

The sensors that is currently available in SensingKit are all event-driven or continuous sensors. iOS does support offline sensors and we do plan to support them in future versions of SensingKit. Unfortunately I don't have an estimate on when that will happen. 

You can access the offline pedometer sensor yourself (but needs to happen outside SensingKit framework). You can finds information here: https://developer.apple.com/documentation/coremotion/cmpedometer
