### ISSUE TITLE
Swift Version

### ISSUE THREAD

**Issue by dimohamdy** [SensingKit/SensingKit-iOS#8]
rewrite SDK  using  swift

**Comment by minoskt** [comment]
Hi @dimohamdy 

At the moment we only focus on the Objective-C version. I understand that a Swift version would look very nice and we are open to that idea. Is that something you would like to contribute in? We would love to hear your ideas about the design of it.

We have tested this version and should work fine under Swift code. Let us know if you experience any problem.

Regards
Minos
