### ISSUE TITLE
Crashing in Airplane mode

### ISSUE THREAD

**Issue by coybit** [SensingKit/SensingKit-iOS#9]
After calling startContinuousSensingWithSensor: for Location, if user turns on Airplane Mode, app crashes. I took a look at the source code and found out that you call abort() inside locationManager:didFailWithError: .
You can choose a better approach for this situation.

**Comment by minoskt** [comment]
Thank you for reporting this issue and sorry for such late reply.

We are working on the next version (v.0.5.0) with support for error handling using NSError. I agree calling abort() was a bad choice but was the only fast solution at that stage. I think the NSError approach will fix this issue.

Best regards
Minos
